### PR TITLE
Adds separate itemized schemas for gen3

### PR DESCRIPTION
**Pull request by bwalsh**
This PR:
* separates itemized yaml schema for gen3 in schemas/gen3
* bmeg schemas moved to schemas/bmeg
* BodyStructure and Encounter added
* Gen3 edges from Observation limited to Patient, ResearchStudy and Specimen

See https://github.com/bmeg/iceberg-schema-tools/pull/5

### CODE REVIEW

**Comment by bwalsh** [comment]
@matthewpeterkort pls review

**Comment by matthewpeterkort** [comment]
refer to [https://github.com/bmeg/iceberg-schema-tools/pull/5](https://github.com/bmeg/iceberg-schema-tools/pull/5)

**Comment by bwalsh** [comment]
@matthewpeterkort  updated https://github.com/bmeg/iceberg/pull/6/commits/57ff00a789edc955922415488f0e67ea63b0433d

**Comment by matthewpeterkort** [comment]
Ok LGTM now

**Pull request merged**
