### PR TITLE
Adds hypermedia links

### PR DESCRIPTION
**Pull request by bwalsh**
This PR adds results of `iceberg schema generate graph` ( see https://github.com/bmeg/iceberg-schema-tools/pull/22)

### CODE REVIEW

**Comment by bwalsh** [comment]
@evergreen700 can you review?

**Review by evergreen700 — COMMENTED** [review]
Seems pretty consistent! I do wonder a bit at why the links property is always double nested, do the BMEG schemas need to change to reflect that? I don't think we were doing it that way before

**Comment by bwalsh** [comment]
> Seems pretty consistent! I do wonder a bit at why the links property is always double nested, do the BMEG schemas need to change to reflect that? I don't think we were doing it that way before

https://github.com/bmeg/iceberg/pull/11/files#diff-0fd054f3a475f3e9279e56f3665880ed9779a547ce4766a5c1ae22ac42e581e4R143-R147

I see what you mean.   That is an issue that needs to be fixed.

I think the issue is here.   https://github.com/bmeg/iceberg-schema-tools/blob/0549f9d2e8cc12e799d1b794b1e2ef8dacdb3fdd/iceberg_tools/graph/__init__.py#L522-L523

**Review by evergreen700 — COMMENTED** [review]
I'm confused about why there are so many identical links in the description field of most schemas. If it's just in the description I suppose it has no effect on the functionality of the schema, but it is annoying, especially for schemas with 8+ copies in the description

**Pull request merged**
